# Generated by Django 2.2.13 on 2021-04-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginApp', '0003_auto_20210409_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorites', to='loginApp.User')),
                ('watch_later', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to='loginApp.User')),
            ],
        ),
    ]
